### ISSUE TITLE
Feature Request: replace `chrono`

### ISSUE THREAD

**Issue by jqnatividad** [waltzofpearls/dateparser#22]
Given `chrono`'s unresolved security advisory - https://rustsec.org/advisories/RUSTSEC-2020-0159,

It'd be nice if dateparser is re-implemented without it.

**Comment by waltzofpearls** [comment]
Hey @jqnatividad, thanks for reporting this issue. I went through this issue https://github.com/chronotope/chrono/issues/499 and saw someone suggested using https://github.com/x-hgg-x/tz-rs for localtime call. I will dig a little deeper and also see if there are alternatives to `chrono`.

**Comment by kdwarn** [comment]
This was fixed. See https://github.com/chronotope/chrono/issues/499 and https://github.com/chronotope/chrono/pull/677
